/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsNumber, IsOptional, ValidateNested } from "class-validator";
import { ProductCreateNestedManyWithoutDiscountsInput } from "./ProductCreateNestedManyWithoutDiscountsInput";
import { Type } from "class-transformer";
import { PromotionCreateNestedManyWithoutDiscountsInput } from "./PromotionCreateNestedManyWithoutDiscountsInput";
import { UserCreateNestedManyWithoutDiscountsInput } from "./UserCreateNestedManyWithoutDiscountsInput";

@InputType()
class DiscountCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  Percentage?: number | null;

  @ApiProperty({
    required: false,
    type: () => ProductCreateNestedManyWithoutDiscountsInput,
  })
  @ValidateNested()
  @Type(() => ProductCreateNestedManyWithoutDiscountsInput)
  @IsOptional()
  @Field(() => ProductCreateNestedManyWithoutDiscountsInput, {
    nullable: true,
  })
  product?: ProductCreateNestedManyWithoutDiscountsInput;

  @ApiProperty({
    required: false,
    type: () => PromotionCreateNestedManyWithoutDiscountsInput,
  })
  @ValidateNested()
  @Type(() => PromotionCreateNestedManyWithoutDiscountsInput)
  @IsOptional()
  @Field(() => PromotionCreateNestedManyWithoutDiscountsInput, {
    nullable: true,
  })
  promotions?: PromotionCreateNestedManyWithoutDiscountsInput;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutDiscountsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutDiscountsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutDiscountsInput, {
    nullable: true,
  })
  user?: UserCreateNestedManyWithoutDiscountsInput;
}

export { DiscountCreateInput };
