/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsNumber,
} from "class-validator";
import { DiscountCreateNestedManyWithoutProductsInput } from "./DiscountCreateNestedManyWithoutProductsInput";
import { Type } from "class-transformer";
import { KitCreateNestedManyWithoutProductsInput } from "./KitCreateNestedManyWithoutProductsInput";
import { OrderCreateNestedManyWithoutProductsInput } from "./OrderCreateNestedManyWithoutProductsInput";
@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => DiscountCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => DiscountCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => DiscountCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  discounts?: DiscountCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  itemPrice?: number | null;

  @ApiProperty({
    required: false,
    type: () => KitCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => KitCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => KitCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  kits?: KitCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  orders?: OrderCreateNestedManyWithoutProductsInput;
}
export { ProductCreateInput };
